
default_platform(:ios)

platform :ios do
  before_all do
    setup_ci
  end

  desc "Build and Sign the binary"
  lane :build do
    match(type: "appstore", readonly: true)
    gym(
      scheme: "getting started",
      export_method: "app-store"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true)

    app_store_connect_api_key(
      key_id: "S3SVC2YV67",
      issuer_id: "69a6de7b-8428-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./secrets/AuthKey_S3SVC2YV67.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    increment_build_number(xcodeproj: "getting started.xcodeproj")
    build_app(scheme: "getting started")
    upload_to_testflight
  end
end

