# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# keychain is managed outside of Fastlane Match, with command line scripts.
# if you decide to switch to Fastlane Match, you have to change the project signing settings as well.

#unlock_keychain( 
#  path: "/Users/ec2-user/Library/Keychains/dev.keychain-db",
#  password: "Passw0rd",
#  set_default: true
#)

platform :ios do
  
  lane :clean do 
    clean_build_artifacts
    clear_derived_data
  end

  lane :beta do
    desc "Push a new beta build to TestFlight"
    increment_build_number(xcodeproj: "getting started.xcodeproj")
    build # call build lane
    upload_to_testflight
  end
  

  lane :build do
    desc "Build the project"
    build_app(workspace: "getting started.xcworkspace", scheme: "getting started",
              skip_archive: false,
              output_directory: ".build",
              output_name: "getting_started.ipa",
              export_method: "development",
              export_options: {
                 provisioningProfiles: { 
                    "com.amazonaws.amplify.mobile.getting-started" => "match Development com.amazonaws.amplify.mobile.getting-started 1665469423"
                 }
              })
  end

end
