# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# before_all do
#   create_keychain(
#     name: "macos_build",
#     default_keychain: true,
#     unlock: true,
#     timeout: 0,
#     lock_when_sleeps: false,
#     password: "Passw0rd!"
#   )
# end

platform :ios do
  
  lane :clean do 
    clean_build_artifacts
    clear_derived_data
  end

  lane :beta do
    desc "Push a new beta build to TestFlight"
    # match(type: "appstore", readonly: true)
    increment_build_number(xcodeproj: "getting started.xcodeproj")
    build_app(workspace: "getting started.xcworkspace", scheme: "getting started")
    upload_to_testflight
  end
  

  lane :build do
    unlock_keychain( 
        path: "/Users/ec2-user/Library/Keychains/dev.keychain-db",
        password: "Passw0rd",
        set_default: true
    )
    desc "Build the project"
    # match(type: "development", readonly: true)
    build_app(workspace: "getting started.xcworkspace", scheme: "getting started",
              skip_archive: false,
              export_method: "development")
  end

end
